
   exports.co_mod_one_part_one="BQACAgUAAxkBAAIEjGFR9N78SBfh0tRFubvZVKpiPP7IAAJEAwAC-TyIVab3K3jz5EpiIQQ"
   exports.co_mod_one_part_two="BQACAgUAAxkBAAIFKGFR_3zBO3V7XQtqLgABHmVR1f_6UAACSAMAAvk8iFUBK2tPK06l1iEE"
 exports.co_mod_one_part_three="BQACAgUAAxkBAAIFKWFR_3xcnAABvZWb4h2Hzn1T-qgxhgACSgMAAvk8iFVGSmxd5tBGlyEE" 
  exports.co_mod_one_part_four="BQACAgUAAxkBAAIFKmFR_3y5IgHrbexhe8EZBXHhuSiTAAJMAwAC-TyIVSZFaDHIMdt0IQQ"



//
   exports.se_mod_one_part_one="BQACAgUAAxkBAAIEk2FR9kuq5-cmtjY1HXzrbz6bbQaQAAKlAwAC1h6QVvr5d8wO41fkIQQ"

   exports.se_mod_one_part_two='BQACAgUAAxkBAAIElGFR9r-o8vP9Lkx0_qQcFrGo2-mYAAKmAwAC1h6QVuMwzBUPZ_RSIQQ'
   exports.se_mod_one_part_three='BQACAgUAAxkBAAIElWFR9xPuEocind5KYDqKXeKlQSJrAAKnAwAC1h6QVnaCmnZ4y9m1IQQ' 

   exports.se_mod_one_part_four= 'BQACAgUAAxkBAAIElmFR9y7_1htw_IJxbQ4YF4g9JHE2AAKoAwAC1h6QVq8oLHIzpqQ2IQQ'
   exports.se_mod_one_part_five='BQACAgUAAxkBAAIEl2FR91J7nm9nTTvptWeuJJK8UX8nAAKpAwAC1h6QViBNkrFd0xHmIQQ'
   exports.se_mod_one_part_six='BQACAgUAAxkBAAIEmGFR92tNPue3DSvkjiOrIVWdx86dAAKqAwAC1h6QVrBjFhvK_pHnIQQ'
   exports.se_mod_one_part_seven='BQACAgUAAxkBAAIEmWFR95YohqNnMdPBf81TA3G2kjlSAAKrAwAC1h6QVne_2miDwXNrIQQ'
   //

   
