exports.co_mod_five_part_one="BQACAgUAAxkBAAIGQ2FSmsBaQM97xPHq-7AhzLkKKNq7AALAAgAC-TyIVUn0BG5x2X16IQQ"

//

exports.mathsmain_mod_five_pone="BQACAgUAAxkBAAIHIGFTRshK-lwHaKLU6-MkGRjefZoEAALyAwACuRCZViqZ0t0zTu9WIQQ"
exports.mathsmain_mod_five_ptwo="BQACAgUAAxkBAAIHIWFTRsggar2QBxWlVIKMPda-hx1TAAL4AwACEtWZVjMjswvzeGvwIQQ"
exports.mathsmain_mod_five_pthree="BQACAgUAAxkBAAIHImFTRsgJZA0Fp7KygcEeal5IRUraAAL5AwACEtWZVkkgqUMULrXAIQQ"
exports.mathsmain_mod_five_pfour="BQACAgUAAxkBAAIHI2FTRshWIL0es9m2gpA6zVlOtmHBAAL6AwACEtWZVixLc3K4DHZiIQQ"
exports.mathsmain_mod_five_pfive="BQACAgUAAxkBAAIHJGFTRsit83qewHLoYiQc4GUV3HVHAAL7AwACEtWZVk5Z-twC1e3VIQQ"
exports.mathsmain_mod_five_psix="BQACAgUAAxkBAAIHJWFTRshE1pjzV4xHyMBRlZpjHOpbAAL8AwACEtWZVg81LhGkxfBOIQQ"node
